GET http://localhost:3000/posts
Authorization: Bearer <ACCESS_TOKEN>

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "<REFRESH_TOKEN>"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
    "token": "<REFRESH_TOKEN>"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "user 2"
}