GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/66a2193b8cec913934efe242

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "user 2",
    "subscriberToChannel": "Channel 2"
}

###

DELETE http://localhost:3000/subscribers/66a2193b8cec913934efe242